name: CICD-DEPLOYUTIL_develop

env:
  nugetFeedName: 'mm365'

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        type: choice
        options:
          - dev
          - e2e
          - qa
          - citest
          - cso
          - prod

jobs:
  RESTORE_NUGGET_PACKAGES:
    runs-on: 'windows-latest'
    env:
      finalnugetFeedUrl: "http://tfs.mybank.com:8080/tfs/Default/_packaging/${{ env.nugetFeedName }}/nuget/v3/index.json"
    steps:
      - name: Checkuot ${{ github.event.repository.name }} Repo
        uses: actions/checkout@v3
      - name: Restore NUGET on RUNNER host
        run: |
          Write-host nuget sources add -Name "${{ env.nugetFeedName }}" -ConfigFile nuget.config -Source "${{ env.finalnugetFeedUrl }}"
