name: Echo Secret Value

on:
  push:
    branches:
      - main

jobs:
  echo_value:
    runs-on: ubuntu-latest

    steps:
      - name: Set environment variable
        run: echo "FINALENV=Prod" >> $GITHUB_ENV

      - name: Set interpolated secret name
        id: interpolate_secret
        run: |
          echo "FINALUSER=svd_BUILD${{ env.FINALENV }}" >> $GITHUB_ENV
      
      - name: Print Secret name
        run: |
         echo "USER IS: ${{ env.FINALUSER }}"

      - name: Echo interpolated value
        run: echo "${{ secrets[ env.FINALUSER ] }}"
        
      - name: Check if file exists
        run: |
          if exist "${{ env.FILE_PATH }}"(
          echo File exists!
          ) else (
          echo File does not exist!
          )
  
