name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  mainjob1:
    runs-on: ubuntu-latest

    steps:
      - name: Set Variable
        run: |
          echo "var1=good" >> $GITHUB_OUTPUT

  mainjob2:
    needs: mainjob1
    runs-on: ubuntu-latest

    steps:

      - name: Access Variable
        run: |
          echo "var1=${{ needs.mainjob1.outputs.var1 }}"
