name: Refresh_poc - AD
env:
  DBenv: 'STG'

on:
  push:
    branches:
      - main

jobs:
  SETVARS:
    outputs:
      formatdate: ${{ steps.get-date.outputs.formatdate }}
    runs-on: ubuntu-22.04
    steps:
      - name: Get present date
        id: get-date
        run: |
          date=$(date +"%d%b%Y")
          echo "Date is: $date"
          echo "::set-output name=formatdate::$date"
#          echo "formatdate=$date" >> env.GITHUB_OUTPUT

  TAKING_BACKUP:
    needs: SETVARS
    runs-on: ubuntu-22.04
    steps:
      - name: Taking backup
        run: |
          echo "CO_date_is ${{ needs.SETVARS.outputs.formatdate }}"

  SETVARS1:

    runs-on: ubuntu-22.04

    steps:

      - name: Get present date
        id: get-date
        run: |
          date=$(date +"%d%b%Y")
          echo "Date is: $date"
          echo "formatdate=$date" >> $GITHUB_ENV

  TAKING_BACKUP1:

    needs:
      - SETVARS1

    runs-on: ubuntu-22.04

    steps:   

      - name: Taking backup
        run: |
          echo "CO_date_is $formatdate"
          
          
  SETVARS2:
    runs-on: self-hosted-unixhost1
    steps:
      - name: Get present date
        id: get-date
        run: |
          date=$(date +"%d%b%Y")
          echo "Date is: $date"
          echo "formatdate=$date" >> $GITHUB_ENV
          #echo "::set-output name=formatdate::$date"

  TAKING_BACKUP2:
    needs:
      - SETVARS
    runs-on: self-hosted-unixhost1
    steps:   
      - name: Taking backup
        run: |
          source $GITHUB_ENV
          echo "CO_date_is $formatdate"          
