name: CALLER main yml

on:
  push:
    branches: main
  workflow_dispatch:  
    
    inputs:
      key_name:
        required: true
        default: 'app_name'
   
jobs:
  mainjob1:
    runs-on: "windows-latest"
    
    outputs:
      app_namexx: ${{ steps.run-script.outputs.[key_name] }}  

    steps:        
      - name: Checkout  repository
        uses: actions/checkout@v3
